name: Train Tracker

on:
  schedule:
    - cron: "*/30 7-23 * * *"

  workflow_dispatch:

jobs:

  run:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - run: python app/main.py
        env:
          TRANSPORT_API_ID: ${{ secrets.TRANSPORT_API_ID }}
          TRANSPORT_API_KEY: ${{ secrets.TRANSPORT_API_KEY }}

          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
